### ISSUE TITLE
(Reopen) get data

### ISSUE THREAD

**Issue by TapsHTS** [tonylin0826/yeelight.io#2]
Sorry, I have a problem @tonylin0826, when I do:
```js
const { Bulb } = require('yeelight.io');
const l1 = new Bulb('192.168.X.XX');

l1.connect();
console.log(l1.props);
```
It return
```
{}
```
It's normal ?

**Comment by tonylin0826** [comment]
If there isn't a state change for the light, there will be no props in this object, this object updates when a notification is sent from the light bulb. 

`bulb.props` stores the data received from [4.3 NOTIFICATION message](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf). Please try changing the state of the bulb and see if the props are updated

**Comment by TapsHTS** [comment]
When you say "isn't a state change for the light" what did you want to say ? The on/off state ? The color state ? If you can do an exemple for get the on/off state thank's.

**Comment by tonylin0826** [comment]
I currently don't have a yee light with me. Lete get one and get back to you

**Comment by TapsHTS** [comment]
Okay no problem thank's so much.

**Comment by tonylin0826** [comment]
@TapsHTS 

Below is the example code to get on/off state from `bulb.props`.

```javascript
'use strict'

const { Bulb } = require('yeelight.io');
const l1 = new Bulb('192.168.1.217');

l1.on('props', () => {
  console.log(l1.props)
})

l1.on('connected', () => {
  l1.toggle()
})

l1.connect();
```

I am thinking to maybe add a method to query all state from the bulb, will check Yeelight spec to see if they support it or not.

**Comment by tonylin0826** [comment]
@TapsHTS I also release a newer version that support `bulb.getProps`. It queries the props from yeelight get set the received props to `bulb.props`, you can find the example in `example/props.example.js` or [here](https://github.com/tonylin0826/yeelight.io#instancegetprops)

**Comment by TapsHTS** [comment]
Thank's you. ! Reassure me you didn’t buy any light for this occasion anyway ? 😂

**Comment by TapsHTS** [comment]
@tonylin0826 Is there an alternative to the `l1.on('props')` event of the `l1.getProps.power ` style? Because my goal is to create an express server or when we make a request to the link it returns the status of the bulb but I don't think I can use an event.

```js
app.post(`/yeelight/${data.web.security_token}/data/:name`, (req, res) => {

    const name = req.params.name

    try {
        if (name === "light") {
            l1.on('props', () => {
                return res.status(202).json({
                    status: 'status: ' + l1.props.power
                })
            })
            l1.getProps()
        }
    } catch (error) {
        console.log(error)
        return res.status(404).json({
            status: 'error: ' + error
        })

    }
})
```
Here is the code I am using but it return this error:
```
TypeError: Cannot read property 'set' of undefined
    at Bulb.sendCmd (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:198:25)
    at Bulb.getProps (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:167:10)
```

**Comment by tonylin0826** [comment]
@TapsHTS I think you are missing `connect` in your code. Can you try calling your express post handler after l1 is connected?

**Comment by tonylin0826** [comment]
Something like this should work

```javascript
app.post(`/yeelight/${data.web.security_token}/data/:name`, (req, res) => {
  const name = req.params.name

  try {
    if (name === 'light') {
      const l1 = new Bulb('192.168.xxx.xxx')

      l1.on('props', () => {
        return res.status(202).json({
          status: 'status: ' + l1.props.power
        })
      })

      l1.on('connected', () => {
        l1.getProps()
      })

      l1.connect()
    }
  } catch (error) {

    console.log(error)
    return res.status(404).json({
      status: 'error: ' + error
    })
  }
})
```

**Comment by TapsHTS** [comment]
I try that and i will back to you. 👍

**Comment by TapsHTS** [comment]
Ok i think is good ! Thank's so muck @tonylin0826 !

**Comment by TapsHTS** [comment]
ok after several tests I noticed that when we turn on the light that we get the props, that we turn off and that we get the props it return an big error 
```js
node:events:385
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Bulb {
  _events: [Object: null prototype] {
    props: [Function (anonymous)],
    connected: [Function (anonymous)]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  ip: '192.168.0.41',
  port: 55443,
  _supportedProps: [
    'power',          'bright',
    'ct',             'rgb',
    'hue',            'sat',
    'color_mode',     'flowing',
    'delayoff',       'flow_params',
    'music_on',       'name',
    'bg_power',       'bg_flowing',
    'bg_flow_params', 'bg_ct',
    'bg_lmode',       'bg_bright',
    'bg_rgb',         'bg_hue',
    'bg_sat',         'nl_br'
  ],
  client: <ref *1> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      data: [Function: bound _onData],
      close: [Function: bound _onClose],
      error: [Function: bound _onError]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    [Symbol(async_id_symbol)]: 12,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    [Symbol(kSetNoDelay)]: false,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  cmdId: 1,
  props: {
    power: 'on',
    bright: '100',
    ct: '4000',
    rgb: '16711680',
    hue: '359',
    sat: '100',
    color_mode: '2',
    flowing: '0',
    delayoff: '0',
    flow_params: '',
    music_on: '0',
    name: '',
    bg_power: '',
    bg_flowing: '',
    bg_flow_params: '',
    bg_ct: '',
    bg_lmode: '',
    bg_bright: '',
    bg_rgb: '',
    bg_hue: '',
    bg_sat: '',
    nl_br: ''
  },
  messageHandler: { props: [Function: bound onProps] },
  waitingRequest: Map(0) {},
  [Symbol(kCapture)]: false
})
    at new NodeError (node:internal/errors:371:5)
    at Bulb.emit (node:events:383:17)
    at Bulb._onError (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:113:10)
    at Bulb._onData (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:100:12)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  code: 'ERR_UNHANDLED_ERROR',
  context: Bulb {
    _events: [Object: null prototype] {
      props: [Function (anonymous)],
      connected: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    ip: '192.168.0.41',
    port: 55443,
    _supportedProps: [
      'power',          'bright',
      'ct',             'rgb',
      'hue',            'sat',
      'color_mode',     'flowing',
      'delayoff',       'flow_params',
      'music_on',       'name',
      'bg_power',       'bg_flowing',
      'bg_flow_params', 'bg_ct',
      'bg_lmode',       'bg_bright',
      'bg_rgb',         'bg_hue',
      'bg_sat',         'nl_br'
    ],
    client: <ref *1> Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: [],
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: false,
        constructed: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: true,
        destroyed: false,
        errored: null,
        closed: false,
        closeEmitted: false,
        defaultEncoding: 'utf8',
        awaitDrainWriters: null,
        multiAwaitDrain: false,
        readingMore: false,
        dataEmitted: true,
        decoder: null,
        encoding: null,
        [Symbol(kPaused)]: false
      },
      _events: [Object: null prototype] {
        end: [Function: onReadableStreamEnd],
        data: [Function: bound _onData],
        close: [Function: bound _onClose],
        error: [Function: bound _onError]
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        afterWriteTickInfo: null,
        buffered: [],
        bufferedIndex: 0,
        allBuffers: true,
        allNoop: true,
        pendingcb: 0,
        constructed: true,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: true,
        errored: null,
        closed: false,
        closeEmitted: false,
        [Symbol(kOnFinished)]: []
      },
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(async_id_symbol)]: 12,
      [Symbol(kHandle)]: TCP {
        reading: true,
        onconnection: null,
        [Symbol(owner_symbol)]: [Circular *1]
      },
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    cmdId: 1,
    props: {
      power: 'on',
      bright: '100',
      ct: '4000',
      rgb: '16711680',
      hue: '359',
      sat: '100',
      color_mode: '2',
      flowing: '0',
      delayoff: '0',
      flow_params: '',
      music_on: '0',
      name: '',
      bg_power: '',
      bg_flowing: '',
      bg_flow_params: '',
      bg_ct: '',
      bg_lmode: '',
      bg_bright: '',
      bg_rgb: '',
      bg_hue: '',
      bg_sat: '',
      nl_br: ''
    },
    messageHandler: { props: [Function: bound onProps] },
    waitingRequest: Map(0) {},
    [Symbol(kCapture)]: false
  }
}
```

**Comment by TapsHTS** [comment]
ok @tonylin0826  after several tests I noticed that when we turn on the light that we get the props, that we turn off and that we get the props it return an big error 
```js
node:events:385
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Bulb {
  _events: [Object: null prototype] {
    props: [Function (anonymous)],
    connected: [Function (anonymous)]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  ip: '192.168.0.41',
  port: 55443,
  _supportedProps: [
    'power',          'bright',
    'ct',             'rgb',
    'hue',            'sat',
    'color_mode',     'flowing',
    'delayoff',       'flow_params',
    'music_on',       'name',
    'bg_power',       'bg_flowing',
    'bg_flow_params', 'bg_ct',
    'bg_lmode',       'bg_bright',
    'bg_rgb',         'bg_hue',
    'bg_sat',         'nl_br'
  ],
  client: <ref *1> Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      data: [Function: bound _onData],
      close: [Function: bound _onClose],
      error: [Function: bound _onError]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    [Symbol(async_id_symbol)]: 12,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    [Symbol(kSetNoDelay)]: false,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  cmdId: 1,
  props: {
    power: 'on',
    bright: '100',
    ct: '4000',
    rgb: '16711680',
    hue: '359',
    sat: '100',
    color_mode: '2',
    flowing: '0',
    delayoff: '0',
    flow_params: '',
    music_on: '0',
    name: '',
    bg_power: '',
    bg_flowing: '',
    bg_flow_params: '',
    bg_ct: '',
    bg_lmode: '',
    bg_bright: '',
    bg_rgb: '',
    bg_hue: '',
    bg_sat: '',
    nl_br: ''
  },
  messageHandler: { props: [Function: bound onProps] },
  waitingRequest: Map(0) {},
  [Symbol(kCapture)]: false
})
    at new NodeError (node:internal/errors:371:5)
    at Bulb.emit (node:events:383:17)
    at Bulb._onError (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:113:10)
    at Bulb._onData (D:\Users\legot\Visual\ikeapi\node_modules\yeelight.io\yeelight.js:100:12)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  code: 'ERR_UNHANDLED_ERROR',
  context: Bulb {
    _events: [Object: null prototype] {
      props: [Function (anonymous)],
      connected: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    ip: '192.168.0.41',
    port: 55443,
    _supportedProps: [
      'power',          'bright',
      'ct',             'rgb',
      'hue',            'sat',
      'color_mode',     'flowing',
      'delayoff',       'flow_params',
      'music_on',       'name',
      'bg_power',       'bg_flowing',
      'bg_flow_params', 'bg_ct',
      'bg_lmode',       'bg_bright',
      'bg_rgb',         'bg_hue',
      'bg_sat',         'nl_br'
    ],
    client: <ref *1> Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: [],
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: false,
        constructed: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: true,
        destroyed: false,
        errored: null,
        closed: false,
        closeEmitted: false,
        defaultEncoding: 'utf8',
        awaitDrainWriters: null,
        multiAwaitDrain: false,
        readingMore: false,
        dataEmitted: true,
        decoder: null,
        encoding: null,
        [Symbol(kPaused)]: false
      },
      _events: [Object: null prototype] {
        end: [Function: onReadableStreamEnd],
        data: [Function: bound _onData],
        close: [Function: bound _onClose],
        error: [Function: bound _onError]
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        afterWriteTickInfo: null,
        buffered: [],
        bufferedIndex: 0,
        allBuffers: true,
        allNoop: true,
        pendingcb: 0,
        constructed: true,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: true,
        errored: null,
        closed: false,
        closeEmitted: false,
        [Symbol(kOnFinished)]: []
      },
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(async_id_symbol)]: 12,
      [Symbol(kHandle)]: TCP {
        reading: true,
        onconnection: null,
        [Symbol(owner_symbol)]: [Circular *1]
      },
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    cmdId: 1,
    props: {
      power: 'on',
      bright: '100',
      ct: '4000',
      rgb: '16711680',
      hue: '359',
      sat: '100',
      color_mode: '2',
      flowing: '0',
      delayoff: '0',
      flow_params: '',
      music_on: '0',
      name: '',
      bg_power: '',
      bg_flowing: '',
      bg_flow_params: '',
      bg_ct: '',
      bg_lmode: '',
      bg_bright: '',
      bg_rgb: '',
      bg_hue: '',
      bg_sat: '',
      nl_br: ''
    },
    messageHandler: { props: [Function: bound onProps] },
    waitingRequest: Map(0) {},
    [Symbol(kCapture)]: false
  }
}
```

**Comment by tonylin0826** [comment]
@TapsHTS Do you have a script that ca reproduce this problem?

**Comment by TapsHTS** [comment]
@tonylin0826 I try to create that
